### ISSUE TITLE
A resolve function's info.fieldASTs value has been renamed to info.fieldNodes

### ISSUE THREAD

**Issue by gitawego** [du5rte/graphql-mongodb-projection#3]
thanks for your great lib, but recently, the field ``fieldASTs`` is renamed to ``fieldNodes`` in graphql-js [v0.8.0](https://github.com/graphql/graphql-js/releases/tag/v0.8.0)

could you please adapt this change ?

**Comment by du5rte** [comment]
@gitawego sure thanks for letting me know, do you want to submit those changes? I haven't used graphQL in a while let me know if there's anything else I should be aware of. Thanks 👍

**Comment by gitawego** [comment]
thanks for accepting the PR. could you please release a new version in npm when you have time ? so I can update via ``npm update`` ^^

thanks a lot.

**Comment by du5rte** [comment]
@gitawego yeh just bumped it to 1.0.5 :) thanks for the PR 👌
